const Hero = () => {
  return (
    <>
      <div
        className=" pb-10"
        style={{
          background:
            "radial-gradient(1200px 600px at 80% -10%, rgba(29, 78, 216, 0.25), transparent 60%), radial-gradient(900px 500px at 10% -10%, rgba(56, 189, 248, 0.25), transparent 60%)",
        }}
      >
        <section
          id="home"
          className="pt-24 pb-16 md:pt-32 md:pb-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto"
        >
          <div className="flex flex-col md:flex-row items-center">
            <div className="md:w-1/2 mb-12 md:mb-0 fade-in">
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight mb-6">
                Build fast. <br />
                <span className="gradient-text">Deploy anywhere.</span>
              </h1>
              <p className="text-lg md:text-xl text-slate-600 dark:text-slate-300 mb-8">
                We design, develop, and deploy full-stack web apps and cloud
                infrastructure that scale.
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <a
                  href="#contact"
                  className="bg-primary hover:bg-blue-800 text-white font-medium py-3 px-6 rounded-lg transition-all text-center shadow-lg"
                >
                  Get a proposal
                </a>
                <a
                  href="#work"
                  className="border-2 border-primary text-primary hover:bg-primary hover:text-white font-medium py-3 px-6 rounded-lg transition-all text-center"
                >
                  See our work
                </a>
              </div>
            </div>
            <div className="md:w-1/2 relative h-64 md:h-96 fade-in-delay-1">
              {/* 3D Nodes Simulation */}
              <div id="nodesContainer" className="w-full h-full relative">
                {/* Nodes and connectors will be generated by JavaScript */}
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
};

export default Hero;
